<a href="<?=App::config('url')?>operater/novi" class="small button">
Dodaj novog operatera
</a>

<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Email</th>
            <th>Uloga</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td><?=$red->ime?></td>
                <td><?=$red->prezime?></td>
                <td><?=$red->email?></td>
                <td><?=$red->uloga?></td>
                <td>
                <a href="<?=App::config('url')?>operater/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>
                <?php if($red->email!=='admin@hardshop.hr' && $red->email!=='operater@hardshop.hr'): ?>
                        <a onclick="return confirm('Potvrdi za brisanje operatera <?=$red->ime?> <?=$red->prezime?>');"
                        href="<?=App::config('url')?>operater/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                    <?php else: ?>
                        <i title="Nije moguće brisati admina"
                        class="fi-trash" style="color: gray"></i>
                    <?php endif; ?>
                    
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>