<a href="<?=App::config('url')?>operater/novi" class="button success expanded">
Dodaj novog operatera
</a>

<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Email</th>
            <th>Uloga</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td><?=$red->ime?></td>
                <td><?=$red->prezime?></td>
                <td><?=$red->email?></td>
                <td><?=$red->uloga?></td>
                <td>
                <a href="<?=App::config('url')?>operater/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>
                <a href=""><i class="fi-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>