<a href="<?=App::config('url')?>kupac/novi" class="button success expanded">
    Dodaj novog kupca
</a>

<table>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Email</th>
            <th>Adresa za račun</th>
            <th>Adresa za dostavu</th>
            <th>Broj telefona</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td><?=$red->ime?></td>
                <td><?=$red->prezime?></td>
                <td><?=$red->email?></td>
                <td><?=$red->adresazaracun?></td>
                <td><?=$red->adresazadostavu?></td>
                <td><?=$red->brojtelefona?></td>
                <td>
                    <a href="<?=App::config('url')?>kupac/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>
                    <?php if($red->narudzba===0): ?>
                        <a onclick="return confirm('Potvrdi za brisanje kupca <?=$red->ime?> <?=$red->prezime?>');"
                        href="<?=App::config('url')?>kupac/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                    <?php else: ?>
                        <i title="Kupca nije moguće brisati jer se nalazi u narudžbi"
                        class="fi-trash" style="color: gray"></i>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
    </tbody>
</table>