<label for="brojnarudzbe">Broj narudžbe*</label>
<input type="text" id="input" name="brojnarudzbe" value="<?=$e->brojnarudzbe?>">

<label for="datumnarudzbe">Datum narudžbe*</label>
<input type="date" name="datumnarudzbe" id="input"
value="<?=$e->datumnarudzbe?>">

<label for="datumisporuke">Datum isporuke</label>
<input type="date" name="datumisporuke" id="input"
value="<?=$e->datumisporuke?>">

<label for="datumplacanja">Datum plaćanja</label>
<input type="date" name="datumplacanja" id="input"
value="<?=$e->datumplacanja?>"> 

<label for="kupac">Kupac*</label>
<select name="kupac" id="input">
    <?php foreach($kupci as $kupac): ?>
        <option 
        <?php if($kupac->sifra==$e->kupac){
            echo ' selected="selected" ';
        } ?>
        value="<?=$kupac->sifra?>">
            <?=$kupac->ime?> <?=$kupac->prezime?>
        </option>
    <?php endforeach;?>
</select>


<label for="placanje">Vrsta plaćanja*</label>
<select name="placanje" id="input">
    <?php foreach($placanja as $placanje): ?>
        <option 
        <?php if($placanje->sifra==$e->placanje){
            echo ' selected="selected" ';
        } ?>
        value="<?=$placanje->sifra?>">
            <?=$placanje->vrstaplacanja?>
        </option>
    <?php endforeach;?>
</select>




