<label for="brojnarudzbe">Broj narudžbe*</label>
<input type="text" id="input" name="brojnarudzbe" value="<?= $e->brojnarudzbe ?>">

<label for="placanje">Vrsta plaćanja*</label>
<select name="placanje" id="input">
    <?php foreach ($placanja as $placanje) : ?>
        <option <?php if ($placanje->sifra == $e->placanje) {
                    echo ' selected="selected" ';
                } ?> value="<?= $placanje->sifra ?>">
            <?= $placanje->vrstaplacanja ?>
        </option>
    <?php endforeach; ?>
</select>

<label for="datumnarudzbe">Datum narudžbe*</label>
<input type="date" name="datumnarudzbe" id="input" value="<?= $e->datumnarudzbe ?>">

<label for="datumisporuke">Datum isporuke</label>
<input type="date" name="datumisporuke" id="input" value="<?= $e->datumisporuke ?>">

<label for="datumplacanja">Datum plaćanja</label>
<input type="date" name="datumplacanja" id="input" value="<?= $e->datumplacanja ?>">

<hr><label for="kupac">Kupac*</label>
    <input type="text" id="uvjetkupac" placeholder="Traži kupca">
    <input type="hidden" name="kupac" id="kupac" value="<?= $kupac->sifra ?>">
    <div id="kupacIme">
        <?=$kupac->ime?> <?=$kupac->prezime?>
    </div>