<div class="popisproizvoda">
    <hr><label for="proizvod">Proizvod*</label>
    <input type="text" id="uvjet" placeholder="Traži proizvod">
    <div style="min-height: 20px;">
        <div style="font-size: 1rem;" id="poruka"></div>
    </div>
</div>
<div class="callout">
    <div id="podaci">
        <?php foreach ($e->proizvodi as $p) : ?>

            <?= $p->naziv ?>

            <a href="#" class="odabraniProizvod" id="p_<?= $p->sifra ?>">
                <i class="fi-trash"></i><br>
            </a>

        <?php endforeach; ?>

    </div>
</div>
<hr>