<form action="" method="post">
    <fieldset class="fieldset">
        <legend><?=$legend?><br>(*obavezna polja)</legend>

        <label for="vrstaplacanja">Vrsta plaćanja*</label>
        <input type="text" id="input" name="vrstaplacanja" value="<?=$e->vrstaplacanja?>">

        <hr>
        <h1><?=$poruka?></h1>

        <div class="grid-x grid-padding-x">
            <div class="large-6 cell">
                <a href="<?=App::config('url')?>placanje/index" class="button alert expanded">Odustani</a>
            </div>
            <div class="large-6 cell">
                <input type="submit" class="button success expanded" value="Spremi">
            </div>
        </div>
    </fieldset>
</form>