<a href="<?=App::config('url')?>placanje/novi" class="button success expanded">
    Dodaj novu vrstu plaćanja
</a>

<table>
    <thead>
        <tr>
            <th>Vrsta plaćanja</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td><?=$red->vrstaplacanja?></td>
                <td>
                    <a href="<?=App::config('url')?>placanje/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>
                    <?php if($red->narudzba===0): ?>
                        <a onclick="return confirm('Potvrdi za brisanje vrste plaćanja <?=$red->vrstaplacanja?>');"
                        href="<?=App::config('url')?>placanje/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                    <?php else: ?>
                        <i title="Vrstu plaćanja nije moguće brisati jer se nalazi u narudžbi"
                        class="fi-trash" style="color: gray"></i>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
    </tbody>
</table>