<a href="<?=App::config('url')?>proizvod/novi" class="small button">
    Unesi novi proizvod
</a><br><br>

<form action="" method="get">
    <input type="text" name="uvjet" placeholder="Pretraži proizvode"
    value="<?=$uvjet?>" id="uvjet">
</form>

<br><?php include 'stranicenje.phtml' ?>

<div class="grid-x grid-padding-x">
    <?php foreach($podaci as $red): ?>
        <div class="large-3 medium-6 small-12 cell">
            <br><div class="callout">
            <img class="slika" id="p_<?=$red->sifra?>"
                src="<?=$red->slika?>"
                alt="<?=$red->jedinicnacijena?>" id="img">

                <hr><?=$red->proizvodjac?><br><?=$red->naziv?> <br> <br><?=$red->jedinicnacijena . ' €'?><br><br>
                Stanje:<i class="fi-<?=$red->dostupnost?>"></i><hr>
                <?php
                    $par=['proizvod', $red->naziv . ' ' . $red->proizvodjac, $red->detaljinarudzbe==0];
                include BP_APP . 'view/includes/promjenabrisanje.phtml';
                ?>
            </div>
        </div>
    <?php endforeach;?>
</div>

<br><?php include 'stranicenje.phtml' ?>

<div class="reveal" id="slikaModal" data-reveal>
    <div style="max-height: 300px; overflow: auto;">
        <img id="image" src="" alt="" />
    </div>
  
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>