<a href="<?=App::config('url')?>proizvod/novi" class="small button">
    Dodaj novi proizvod
</a><br><br>

<form action="" method="get">
    <input type="text" name="uvjet" placeholder="Pretraži proizvode"
    value="<?=$uvjet?>" id="search">
</form>

<br><?php include 'stranicenje.phtml' ?>

<div class="grid-x grid-padding-x">
    <?php foreach($podaci as $red): ?>
        <div class="large-3 medium-6 small-12 cell">
            <br><div class="callout">
                <img src="<?=App::config('url')?>public/img/nepoznato.png" 
                id="img" alt="<?=$red->naziv?> <?=$red->proizvodjac?>
                <?=$red->jedinicnacijena?>">

                <hr><h3><?=$red->proizvodjac?><br><?=$red->naziv?> <br> <br><?=$red->jedinicnacijena . ' €'?><br><br>
                Stanje:<i class="fi-<?=$red->dostupnost?>"></i></h3><hr>
                <?php
                    $par=['proizvod', $red->naziv . ' ' . $red->proizvodjac, $red->detaljinarudzbe==0];
                include BP_APP . 'view/includes/promjenabrisanje.phtml';
                ?>
            </div>
        </div>
    <?php endforeach;?>
</div>

<br><?php include 'stranicenje.phtml' ?>