<form action="" method="post">
    <fieldset>
        <legend>Izmjena podataka o proizvodu</legend>

        <label for="naziv">Naziv</label>
        <input type="text" id="naziv" name="naziv" value="<?=$e->naziv?>">

        <label for="proizvodjac">Proizvođač</label>
        <input type="text" id="proizvodjac" name="proizvodjac" value="<?=$e->proizvodjac?>">

        <label for="jedinicnacijena">Jedinična cijena</label>
        <input type="text" id="jedinicnacijena" name="jedinicnacijena" value="<?=$e->jedinicnacijena?>">

        <label for="opis">Opis</label>
        <input type="text" id="opis" name="opis" value="<?=$e->opis?>">

        <label for="dostupnost">Dostupnost</label>
        <input type="radio" id="da" name="dostupnost" value="true"
        <?php if($e->dostupnost) echo 'checked="checked"'; ?>>
        <label for="da">DA</label>
        
        <input type="radio" id="ne" name="dostupnost" value="false"
        <?php if(!$e->dostupnost) echo 'checked="checked"'; ?>>
        <label for="ne">NE</label>

        <hr>
        <h1><?=$poruka?></h1>

        <div class="grid-x grid-padding-x">
            <div class="large-6 cell">
                <a href="<?=App::config('url')?>proizvod/index" class="button alert expanded">Odustani</a>
            </div>
            <div class="large-6 cell">
                <input type="submit" class="button success expanded" value="Spremi izmjene">
            </div>
        </div>
        

    </fieldset>
</form>