<a href="<?=App::config('url')?>detaljinarudzba/novi" class="small button">
    Dodaj nove detalje narudžbe
</a>

<table>
    <thead>
        <tr>
            <th>Broj Narudžbe</th>
            <th>Kupac</th>
            <th>Naziv proizvoda</th>
            <th>Količina proizvoda</th>
            <th>Popust (€)</th>
            <th>Cijena (€)</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td><?=$red->brojnarudzbe?></td>
                <td><?=$red->kupac?></td>
                <td><?=$red->naziv?></td>
                <td><?=$red->kolicina?></td>
                <td><?=$red->popust?></td>
                <td><?=$red->cijena?></td>
                <td>
                <a href="<?=App::config('url')?>detaljinarudzba/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>    
                <?php if($red->brojnarudzbe==0): ?>
                    <a onclick="return confirm('Sigurno obrisati detalje narudžbe <?=$red->brojnarudzbe?>?');"
                    href="<?=App::config('url')?>detaljinarudzba/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                <?php else: ?>
                    <i title="Detalji narudžbe se ne mogu obrisati jer imaju postojeću narudžbu" 
                    class="fi-trash" style="color: gray"></i>
                <?php endif; ?>

            </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>