<form class="log-in-form" method="post" action="<?=App::config('url');?>prijava/autorizacija">
    <h4 class="text-center">Unesite pristupne podatke</h4>
    <label>Email (operater/admin@hardshop.hr)
        <input type="email" name="email" value="operater@hardshop.hr" id="input"> 
    </label>
    <label>Lozinka (password)
    <input type="password" name="password" id="input" value="password">
    </label>
    <p><input type="submit" class="button large" value="Prijava"></input></p>
    <?=$poruka?>
</form>