<form class="log-in-form" method="post" action="<?=App::config('url');?>prijava/registracija">
    <h4 class="text-center">Unesite potrebne podatke</h4>
    <label>Ime
        <input type="text" name="ime" id="input"> 
    </label>
    <label>Prezime
        <input type="text" name="prezime" id="input"> 
    </label>
    <label>Email
        <input type="email" name="email" id="input"> 
    </label>
    <label>Lozinka
    <input type="password" name="password" id="input">
    </label>
    <input type="submit" class="button large" value="Registracija"></input>
</form>